### ISSUE TITLE
Impressed

### ISSUE THREAD

**Issue by cbioley** [neftaly/react-mdl#3]
Really liking the way you're writing your code dude.

I tried to create the TextField component, but I must be missing something. 

That or I simply don't have your genius ^^

Edit: oh, the input had to be wrapped by a form tag
Edit 2: aaaand I lied. My computer obviously thinks it's too hot here and drops a few CPU cycles. It's working fine, sorry.

**Comment by neftaly** [comment]
Hah, it's still a bit messy while I figure out the internals. I'll make it clearer soon, I promise!
